<?php

if(function_exists("register_field_group"))
{
  register_field_group(array (
    'id' => 'acf_tema',
    'title' => 'Tema',
    'fields' => array (
      array (
        'key' => 'field_549414d04b8cb',
        'label' => 'Aktivt tema',
        'name' => 'tema_active',
        'type' => 'radio',
        'required' => 1,
        'choices' => array (
          0 => 'Nej',
          1 => 'Ja',
        ),
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => 0,
        'layout' => 'vertical',
      ),
      array (
        'key' => 'field_54943dfc01ec9',
        'label' => 'Rubrik för temat',
        'name' => 'tema_header',
        'type' => 'text',
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'formatting' => 'html',
        'maxlength' => '',
      ),
      array (
        'key' => 'field_54943a50d657c',
        'label' => 'Temabeskrivning',
        'name' => 'tema_description',
        'type' => 'textarea',
        'instructions' => 'Lite längre beskrivning som visas under rubriken',
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'formatting' => 'none',
      ),
      array (
        'key' => 'field_54941bf052f06',
        'label' => 'Temabild',
        'name' => 'tema_image',
        'type' => 'image',
        'instructions' => 'Bilden skall vara minst 1024x768 pixlar',
        'required' => 1,
        'save_format' => 'object',
        'preview_size' => 'thumbnail',
        'library' => 'all',
      ),
      array (
        'key' => 'field_54941c940936b',
        'label' => 'Temaposter',
        'name' => 'tema_posts',
        'type' => 'flexible_content',
        'instructions' => 'Klicka på "Add Row" och välj mellan de fyra olika utvisningsalternativen',
        'required' => 1,
        'layouts' => array (
          array (
            'label' => 'En post',
            'name' => 'tema_one',
            'display' => 'row',
            'min' => '',
            'max' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_54941d070936c',
                'label' => 'Välj post',
                'name' => 'tema_post',
                'type' => 'relationship',
                'column_width' => '',
                'return_format' => 'object',
                'post_type' => array (
                  0 => 'post',
                  1 => 'artiklar',
                ),
                'taxonomy' => array (
                  0 => 'all',
                ),
                'filters' => array (
                  0 => 'search',
                ),
                'result_elements' => array (
                  0 => 'post_type',
                  1 => 'post_title',
                ),
                'max' => 1,
              ),
            ),
          ),
          array (
            'label' => 'Två poster',
            'name' => 'tema_two',
            'display' => 'row',
            'min' => '',
            'max' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_5497e7002e6a3',
                'label' => 'Välj poster',
                'name' => 'tema_post_two',
                'type' => 'relationship',
                'column_width' => '',
                'return_format' => 'object',
                'post_type' => array (
                  0 => 'post',
                  1 => 'artiklar',
                ),
                'taxonomy' => array (
                  0 => 'all',
                ),
                'filters' => array (
                  0 => 'search',
                ),
                'result_elements' => array (
                  0 => 'post_type',
                  1 => 'post_title',
                ),
                'max' => 2,
              ),
            ),
          ),
          array (
            'label' => 'Tre poster',
            'name' => 'tema_three',
            'display' => 'row',
            'min' => '',
            'max' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_54981a9b5daf8',
                'label' => 'Välj tre poster',
                'name' => 'tema_post_three',
                'type' => 'relationship',
                'column_width' => '',
                'return_format' => 'object',
                'post_type' => array (
                  0 => 'post',
                  1 => 'artiklar',
                ),
                'taxonomy' => array (
                  0 => 'all',
                ),
                'filters' => array (
                  0 => 'search',
                ),
                'result_elements' => array (
                  0 => 'post_type',
                  1 => 'post_title',
                ),
                'max' => 3,
              ),
            ),
          ),
          array (
            'label' => 'Video',
            'name' => 'tema_video',
            'display' => 'row',
            'min' => '',
            'max' => '',
            'sub_fields' => array (
              array (
                'key' => 'field_54a11413d934b',
                'label' => 'Youtube video ID',
                'name' => 'tema_video_id',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_54a11b1e266b9',
                'label' => 'Video header',
                'name' => 'tema_video_header',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
              array (
                'key' => 'field_54a11b34266ba',
                'label' => 'Video brödtext',
                'name' => 'tema_video_text',
                'type' => 'text',
                'column_width' => '',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
              ),
            ),
          ),
        ),
        'button_label' => 'Add Row',
        'min' => '',
        'max' => '',
      ),
    ),
    'location' => array (
      array (
        array (
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'tema',
          'order_no' => 0,
          'group_no' => 0,
        ),
      ),
    ),
    'options' => array (
      'position' => 'acf_after_title',
      'layout' => 'no_box',
      'hide_on_screen' => array (
        0 => 'the_content',
        1 => 'excerpt',
        2 => 'custom_fields',
        3 => 'discussion',
        4 => 'comments',
        5 => 'author',
        6 => 'format',
        7 => 'categories',
        8 => 'tags',
        9 => 'send-trackbacks',
      ),
    ),
    'menu_order' => 0,
  ));
}
